[package]
name = "shadcn-svelte-plus"
version = "0.1.1"
edition = "2021"
description = "shadcn-svelte-plus cli tool"
license = "MIT"
repository = "https://github.com/m1ten/shadcn-svelte-plus"

[dependencies]
reqwest = "0.12"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
