name: Copy components to shared folder and push changes
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Copy components to shared folder
        run: cp -r src/lib/components/ui/* shared
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "$(git log --format=%B -n 1) -shared"
          git push
